version: 1.0.{build}
os:
  - Visual Studio 2017
install:
  - cmake -G "Visual Studio 15 2017 Win64" -H. -Bbuild
build:
  project: ./build/ALL_BUILD.vcxproj
  verbosity: normal
after_build:
- cmd: >-
    cmake --build build --target install
test_script:
- cmd: >-
    .\bin\Debug_x64\Testing\Testing.exe
